### ISSUE TITLE
Update syntax for Python3

### ISSUE THREAD

**Issue by ybnelson** [yugabyte/gcp-deployment-manager#4]
Scripts completes but with the following output:

WARNING: Create operation operation-1584931386873-5a17c984ed78f-9d294c50-1980b818 completed with warnings:
---
code: NOT_CRITICAL_ERROR
message: |-
  The template is incompatible with Python3. Please fix the following errors:
  Exception in instance.jinja
  Traceback (most recent call last):
      return template.render(resource)
      return original_render(self, *args, **kwargs)
      return self.environment.handle_exception(exc_info, True)
      reraise(exc_type, exc_value, tb)
      raise value.with_traceback(tb)
    File "<template>", line 36, in top-level template code
  jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'iteritems'
   Resource: instance.jinja Resource: config
  https://cloud.google.com/deployment-manager/docs/migrate-to-python3

**Comment by bhavin192** [comment]
Hey @ybnelson thank you for reporting the issue, I will take a look at this.

**Comment by bhavin192** [comment]
Should be fixed by https://github.com/yugabyte/gcp-deployment-manager/pull/5
